# app/config.py  
TELEGRAM_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"  
INFURA_PROJECT_ID = "YOUR_INFURA_PROJECT_ID"

# app/config.py  
TELEGRAM_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"  
INFURA_PROJECT_ID = "YOUR_INFURA_PROJECT_ID"